name: Build TurboRepo

on:
  pull_request:
    branches:
      - staging

jobs:
  build:
    name: Build TurboRepo
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.11.0"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the TurboRepo
      - name: Build TurboRepo
        run: npm run build

      # Lint the code
      - name: Lint Code
        run: npm run lint
